# (PART) by discipline {-}
# test

## superscript and subscript

script^superscript^~subscript~

## equation term coloring

https://bookdown.org/yihui/rmarkdown-cookbook/font-color.html

LaTex color

https://latexcolor.com/

https://www.overleaf.com/learn/latex/Using_colors_in_LaTeX

https://latex-tutorial.com/color-latex/#:~:text=To%20summarize%2C%20pyellow!50efined%20colors%20in,when%20loading%20the%20xcolor%20package.

LaTex color methods

color frame

https://tex.stackexchange.com/questions/582748/highlight-equation-with-boxes-and-arrows

color box

https://tex.stackexchange.com/questions/567739/how-to-move-and-size-colorbox

color box with round corners

https://tex.stackexchange.com/questions/568880/color-box-with-rounded-corners

highlighting

https://tex.stackexchange.com/questions/318991/highlighting-math

https://forum.remnote.io/t/highlighting-latex-formulas/149

LyX

https://tex.stackexchange.com/questions/250069/create-a-color-box
https://latexlyx.blogspot.com/2013/12/lyx.html

https://tex.stackexchange.com/questions/635486/prevent-lyx-from-escaping-math-in-color-box-title

Bookdown - conditional display of text and code blocks (LaTeX/PDF vs. HTML)
https://stackoverflow.com/questions/76240244/bookdown-conditional-display-of-text-and-code-blocks-latex-pdf-vs-html

::: {show-in="pdf"}

\begin{align*}
\colorbox{yellow!50}{$F$}= & \colorbox{yellow!50}{$ma$}\\
\end{align*}

https://community.rstudio.com/t/highlighting-text-inline-in-rmarkdown-or-bookdown-pdf/35118/4
\definecolor{hightlightColor}{HTML}{FFFF66}

\begin{align*}
\colorbox{hightlightColor}{$F$}= & \colorbox{yellow!50}{$ma$}\\
\end{align*}

\begin{align*}
\colorbox{hightlightColor}{\ensuremath{F}}= & \colorbox{yellow!50}{\ensuremath{F}}\\
\end{align*}

\begin{equation}
\colorbox{yellow!50}{$F$}=\colorbox{yellow!50}{$ma$}
\end{equation}

$$
\colorbox{hightlightColor}{$F$}=\colorbox{yellow!50}{$ma$}
$$

$$
\colorbox{yellow!50}{$Y = \beta_0 + \beta_1 X_1 + \ldots + \beta_n X_n$}
$$
:::

::: {show-in="html"}

$$
\require{color}
\colorbox{#FFD1DC}{$F$}=\colorbox{#FFD1DC}{$ma$}
$$

:::

## link and reference

\begin{equation}
  E=mc^2
  (\#eq:emc)
\end{equation}

`\@ref(nice-label)` \@ref(nice-label)

`[link to partition][partition]` [link to partition][partition]

`[partition]` `\@ref(partition)`

[partition] [#partition] (\@ref(partition)) \@ref(#partition)

`[equivalence class]` `\@ref(equivalence class)`

[equivalence class] [#equivalence class] (\@ref(equivalence class)) \@ref(#equivalence class)

[equivalence-class] [#equivalence-class] (\@ref(equivalence-class)) \@ref(#equivalence-class)

[equivalence-class.html] [equivalence-class.html#equivalence-class] (\@ref(equivalence-class.html)) \@ref(equivalence-class.html#equivalence-class)

[equivalence relation] [#equivalence relation] (\@ref(equivalence relation)) \@ref(#equivalence relation)

[equivalence-relation] [#equivalence-relation] (\@ref(equivalence-relation)) \@ref(#equivalence-relation)

[equivalence-relation.html] [equivalence-relation.html#equivalence-relation] (\@ref(equivalence-relation.html)) \@ref(equivalence-relation.html#equivalence-relation)

## number and reference equations

https://bookdown.org/yihui/rmarkdown/bookdown-markdown.html#equations

`\#eq:emc` 
`\@ref(eq:emc)`

\begin{align*}
(\#eq:eqclass)
 & C\text{ is an equivalence class of }a\text{ on }A\\
\Leftrightarrow & \left[a\right]_{\sim}=C=\left\{ x\middle|\begin{cases}
a\in A\\
x\in A\\
x\sim a\\
\sim\text{ is an equivalence relation over }A\times A=A^{2}
\end{cases}\right\} \subseteq A\ne\emptyset\\
\Leftrightarrow & \left[a\right]=\left[a\right]_{\sim}=\left\{ x\middle|\begin{cases}
a\in A\\
x\in A\\
x\sim a\\
\sim\text{ is an equivalence relation on }A
\end{cases}\right\} \subseteq A\ne\emptyset\\
\Rightarrow & \left[a\right]_{\sim}=\left\{ x\middle|x\sim a\right\} \subseteq A\ne\emptyset
\end{align*}

https://bookdown.org/yihui/rmarkdown/bookdown-markdown.html#cross-referencing

This cross reference is the Fig. \@ref(fig:parabola-arc-with-points)

https://stackoverflow.com/questions/51595939/bookdown-cross-reference-figure-in-another-file

I ran into the same issue and came up with this solution if you aim at compiling 2 different pdfs. It relies on LaTeX's xr package for cross references: https://stackoverflow.com/a/52532269/576684

## footnote

noun[^202401260000-test-cross-link-1]

[^202401260000-test-cross-link-1]: This is a footnote.

## citation

https://stackoverflow.com/questions/48965247/use-csl-file-for-pdf-output-in-bookdown/49145699#49145699

citation 1[@noauthor_bookdown_2019] citation 2 @noauthor_bookdown_2019

citation 3[@ccjou2009] citation 4 @ccjou2009

## bookdown environment for definition, theorem, proof

https://bookdown.org/yihui/rmarkdown/bookdown-markdown.html

```{theorem, label, name="Theorem Name"}
Here is my theorem.
```

```{proof, , name="Proof Name"}
Here is my proof.
```

```{theorem, pyth, name="Pythagorean theorem"}
For a right triangle, if $c$ denotes the length of the hypotenuse
and $a$ and $b$ denote the lengths of the other two sides, we have

$$a^2 + \color{cyan}b^2 \overset{\ref{eq:emc}}= \color{red}{c^2} $$
```

```{definition, , name="Definition Name"}
Here is my definition.
```

[number and reference equations]

\@ref(eq:eqclass)

\@ref(eq:emc)

\@ref(thm:pyth)

```{r parabola-arc-with-points, echo=FALSE, engine='tikz', out.width='25%', fig.ext=if (knitr:::is_latex_output()) 'pdf' else 'png', fig.cap='parabola arc with points'}
\begin{tikzpicture}[scale=1.0]
  \draw (-1,1) parabola bend (0,0) (2,4);
  \filldraw
    (-1,1) circle (.05)
    ( 0,0) circle (.05)
    ( 1,1) circle (.05)
    ( 2,4) circle (.05);
\end{tikzpicture}
```