# genetics

::: {show-in="html"}
[楊欣洲: genetics](https://www.youtube.com/playlist?list=PLTp0eSi9MdkPp0swo8-VVplaG8bateq7q)
:::

::: {show-in="pdf"}
\begin{CJK}{UTF8}{bsmi}
楊欣洲: genetics https://www.youtube.com/playlist?list=PLTp0eSi9MdkPp0swo8-VVplaG8bateq7q
\end{CJK}
:::

## term

- chromosome
- locus (sl.) loci (pl.)
- marker
- allele
- haplotype
- genotype
- phenotype / trait
    - endophenotype
  
## marker

- large marker: STRP = short tandem repeat polymorphism, STRs = short tandem repeats
    - linkage analysis
    - paternity testing
    - taxonomy
- small marker: SNP = single-nucleotide polymorphism
    - association analysis
    - disease diagnosis
    - pharmacodynamics? drug design / pharmacogenomics = custom drug
- RFLP = restriction fragment length polymorphism
- platform
    - customized: MALDI-TOF MS(= mass spectrometry)
    - whole-genome gene chip
        - Affymetrix
            - Taiwan BioBank: TWB2.0
        - Illumina
    - NGS = next-generation sequencing

## genome project

- HGP = Human Genome Project
    - 20~25K genes
    - 3 billion bps(base pairs)
    - ELSI = ethical, legal, and social issues
    - 99.9% bps are exactly the same in all people
    - germline mutation
        - male : female = 2 : 1
- HapMap = International HapMap Project
    - SNP, haplotype, tag SNP
        - haplotypes are combination of SNPs
        - tag SNPs can identify unique haplotypes
    - HapMap 1 & 2
        - between-ancestry SNP: 1 common SNP per 5 Kb to 1 common SNP per 1 Kb
            - African
            - European
            - East Asian
                - Han Chinese
                - Japanese
    - HapMap 3: more ancestries
- 1000 Genomes Project
    - NGS
    - identify 95% genetic variants with frequencies at least 1%
    - final phase 77M SNPs
    - browser
        - Ensembl GRCh37
        - Ensembl GRCh38 http://asia.ensembl.org/Homo_sapiens/Info/Index
- TWB = Taiwan BioBank
    - browser: TaiwanView https://taiwanview.twbiobank.org.tw/index
    - pricing: https://www.biobank.org.tw/about_price.php
    
- TPMI = Taiwan Precision Medicine Initiative https://tpmi.ibms.sinica.edu.tw/www/precision-medicine/


## linkage analysis

- Mendel $1^{st}$ & $2^{nd}$ laws
    - law of segregation ~ 3 : 1
    - law of assortment ~ 9 : 3 : 3 : 1
- phenotypic model by R.A. Fisher
    - $$P = G + E$$
        - $G$ is the genotypic component
        - $E$ is the environmental component
    - $$P = G + E + G \cdot E$$
      - $G \cdot E$ is the interaction between the genotypic component and environmental component
- linkage = co-segregation = cosegregation
    - $\theta$ = recombination fraction: 1% recombination = 1 crossover per 100 meioses = 1 cM(centiMorgan) on genetic map
- statistical hypothesis testing for in linkage mapping
    - statistical hypothesis testing for categorical trait in linkage mapping: PLA = parametric linkage analysis
        - $H_0$: no linkage $\theta = 0.5$
        - $H_1$: linkage $\theta < 0.5$
    - statistical hypothesis testing for quantitative trait in linkage mapping: VCLA = variance component linkage analysis
        - $H_0$: no linkage $\sigma^2_{q} = 0$
        - $H_1$: linkage $\sigma^2_{q} > 0$
- study design
    - case control
    - trio
    - affected / discordant sib-pair
    - extended pedigree
- data format: linkage format
    - family-based
        - PID = pedigree Id
        - IID = individual Id
        - FID = father Id
        - MID = mother Id
        - gender
        - affection
        - marker
            - M1 = marker 1
            - M2 = marker 2
            - ...
- single major locus model
    - a two-allele $A$ and $a$ locus influences a dichotomous trait
    - allele frequency
        - $p = \mathrm{P}\left(A\right)$
        - $q = \mathrm{P}\left(a\right) = 1-p$
    - penetrance
        - $f_{AA} = \mathrm{P}\left(\text{affected}\mid AA\right)$
        - $f_{Aa} = \mathrm{P}\left(\text{affected}\mid Aa\right) = f_{aA}$
        - $f_{aa} = \mathrm{P}\left(\text{affected}\mid aa\right)$
    - disease mode of inheritance
        - dominant model
            - $\begin{cases}f_{AA} = 1 \\ f_{Aa} = 1 \\ f_{aa} = 0\end{cases}$
        - recessive model
            - $\begin{cases}f_{AA} = 0 \\ f_{Aa} = 0 \\ f_{aa} = 1\end{cases}$
        - additive model
            - $\begin{cases}f_{AA} = 1 \\ f_{Aa} = \frac{1}{2} \\ f_{aa} = 0\end{cases}$
        - phenocopy model
            - $f_{aa} > 0$ perhaps due to environmental cause
        - liability model
            - e.g. $f_{AA},f_{Aa},f_{aa}$ are age-dependent

### PLA = parametric linkage analysis

- LOD score

### VCLA = variance component linkage analysis

- allele-sharing: IBS and IBD
    - IBS = identity-by-state
    - IBD = identity-by-descent

## association analysis

- LD = linkage disequilibrium
- genotype & allele frequency
    - diallelic marker
        - $p_{AA}$
        - $p_{Aa}$
        - $p_{aA}$
        - $p_{aa}$
        - $p_{A}$
        - $p_{a}$
- HWC = Hardy-Weinberg condition
    - HWE = Hardy-Weinberg equilibrium
    - HWD = Hardy-Weinberg disequilibrium
- gametic or haplotype frequency
    - LE = linkage equilibrium
    - LD = linkage disequilibrium