# (PART) by descipline {-}
# mathematics

- formula typesetting
  - TeX
    - LaTeX
      - pdfLaTeX
      - XeLaTeX
      - editor/tool:
        - LyX
        - OverLeaf
        - MathPix Snip
        - Micro$oft Office Word
          - WordTeX https://tomwildenhain.com/wordtex/
            - Pandoc dependent
          - https://superuser.com/questions/1114697/select-a-different-math-font-in-microsoft-word
          - https://www.youtube.com/watch?v=jlX_pThh7z8
        - Micro$oft Office PowerPoint
          - IguanaTeX https://www.jonathanleroux.org/software/iguanatex/
  - MathML
  - MathJax: JavaScript
- symbolic computing
  - Maple:          by MapleSoft
  - Mathematica:    by Wolfram
- numeric computing
  - MatLab:         by MathWorks

[equivalence relation]^[\@ref(equivalence-relation)]^

[equivalence class]^[\@ref(equivalence-class)]^

[partition]^[\@ref(partition)]^

## discipline

::: {show-in="html"}

## learning map

- pure mathematics
  - logic
    - [Shai Ben-David](https://www.youtube.com/playlist?list=PLPW2keNyw-utXOOzLR-Wp1p0eE5LEtv3N)
  - 林秀豪
    - [應數: 2019](https://www.youtube.com/playlist?list=PLS0SUwlYe8cyfYWKPb8v55pCqfw0MnL0T)
      - [1](https://www.youtube.com/playlist?list=PLS0SUwlYe8cy7eNFtSWru7EtJ_yXM94YH)
      - [2](https://www.youtube.com/playlist?list=PLS0SUwlYe8cxiepObAy7dGDs29AdViZdj)
    - 普物
    - 熱物
  - algebra
    - linear algebra
      - [漫士沉思錄: 無痛線代](https://space.bilibili.com/266765166/channel/collectiondetail?sid=1794944)
      - [周志成](https://www.youtube.com/playlist?list=PLP-JUp2VR1LsFtHT-i_vZ3oNFIAc3t_Ju)
        - [線代啟示錄](https://ccjou.wordpress.com/)
      - [3B1B](https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab)
    - abstract algebra
  - analysis
    - real analysis
      - [陳金次](https://www.youtube.com/playlist?list=PLil-R4o6jmGjoxAWZurHXAY0q9yxwXv5F)
    - complex analysis
    - 齊震宇
      - [微積分1](https://www.youtube.com/playlist?list=PLVJXJebpO4PhAc21JW-cYbzT3sq4s7Qg8)
      - [微積分2](https://www.youtube.com/playlist?list=PLil-R4o6jmGihq7XzdNzb0d5hHqEJbr6L)
      - [分析1](https://www.youtube.com/playlist?list=PLil-R4o6jmGhUqtKbZf0LIFKd-xN__g_M)
      - [分析2](https://www.youtube.com/playlist?list=PLil-R4o6jmGhkuZPmKL_A5Y7N4HOsa1nX)
      - [複變函數](https://www.youtube.com/playlist?list=PLDeGIcQNsaL7FnyhQhaVO7JU231RCYxnl)
    - 林琦焜
      - [Fourier analysis](https://www.youtube.com/playlist?list=PLj6E8qlqmkFuX5N1O3FKoDfoySC6Hku-2)
      - [vector analysis](https://www.youtube.com/playlist?list=PLj6E8qlqmkFuFrce6JQR-FGxM2rIbXUvr)
      - [calculus of variation](https://www.youtube.com/playlist?list=PLj6E8qlqmkFviK2-k7f-XjBLx3_37BPoP)
      - [PDE1](https://www.youtube.com/playlist?list=PLj6E8qlqmkFsD6ppAsmxs-VnWWo9uwWTK)
      - [PDE2](https://www.youtube.com/playlist?list=PLj6E8qlqmkFvOYhjGCYMnrF4oQ-8eH91H)
    - tensor analysis
- applied mathematics
  - statistics
    - 洪弘
      - [mathematical statistics](https://www.youtube.com/playlist?list=PLTpF-A8hKVUOqfNyA6mOD6lo2cc6clZZP)
      - [biostatistics](https://www.youtube.com/playlist?list=PLTp0eSi9MdkNZB4kyLSzIXIUy9JQOJ5AM)
    - [陳鄰安](https://www.youtube.com/playlist?list=PLTpF-A8hKVUPXtNAX9lro-leGgEK0OSEW)
    - [張翔](https://www.youtube.com/@shiangsir/playlists)/廖崇智
    - [楊欣洲: genetics](https://www.youtube.com/playlist?list=PLTp0eSi9MdkPp0swo8-VVplaG8bateq7q)
    - [王超辰: 醫學統計學/LSHTM notes](https://bookdown.org/ccwang/medical_statistics6/)
  - computer graphics
    - Cem Yuksel
      - [get into your slides with OBS](https://www.youtube.com/playlist?list=PLplnkTzzqsZT2-rLDXArSi8LnhWQu0mqv)
      - [introduction](https://www.youtube.com/playlist?list=PLplnkTzzqsZTfYh4UbhLGpI5kGd5oW_Hh)
      - [interactive](https://www.youtube.com/playlist?list=PLplnkTzzqsZS3R5DjmCQsqupu43oS9CFN)

:::