# Python

https://bookdown.org/yihui/rmarkdown/language-engines.html

```{r, eval=TRUE, cache=TRUE}
names(knitr::knit_engines$get())
```
https://rstudio.github.io/reticulate/articles/python_packages.html

```{python, eval=TRUE, cache=TRUE}
x = 'hello, python world!'
print(x.split(' '))
```

```{r, eval=FALSE, cache=TRUE}
library(reticulate)
virtualenv_python()
```

```{r, eval=FALSE, cache=TRUE}
library(reticulate)
# conda_list()
```

```{r, eval=FALSE, cache=TRUE}
library(reticulate)
virtualenv_list()
```

https://rstudio.github.io/reticulate/reference/install_python.html

```{r, eval=FALSE, cache=TRUE}
library(reticulate)
version <- "3.9.12"
# install_python(version)

# create a new environment
# virtualenv_create("r-reticulate", version = version)

# use_virtualenv("r-reticulate")

# install MatPlotLib
# virtualenv_install("r-reticulate", "matplotlib")

# import MatPlotLib (it will be automatically discovered in "r-reticulate")
matplotlib <- import("matplotlib")
```

copy `C:\Users\RW\AppData\Local\r-reticulate\r-reticulate\pyenv\pyenv-win\versions\3.9.12\tcl\tcl8.6` and `C:\Users\RW\AppData\Local\r-reticulate\r-reticulate\pyenv\pyenv-win\versions\3.9.12\tcl\tk8.6` two folders to the folder `C:\Users\RW\AppData\Local\r-reticulate\r-reticulate\pyenv\pyenv-win\versions\3.9.12\Lib`

```{r, eval=FALSE, cache=TRUE}
# library(reticulate)
# use_virtualenv("r-reticulate")
# # matplotlib <- import("matplotlib")
# matplotlib$use("Agg", force = TRUE)
```

```{python, eval=TRUE, cache=TRUE}
import matplotlib.pyplot as plt
plt.plot([0, 2, 1, 4])
plt.show()
```